server:
  port: 8082
spring:
  profiles: prod

#  datasource:
#    url: jdbc:mysql://localhost/tacocloud
#    username: tacouser
#    password: tacopassword
  jpa:
    show-sql: true

taco:
  orders:
    pageSize: 10

  discount:
    codes:
      abcdef: 10

logging:
  level:
    tacos: WARN